Exclude filters
Netsach/concrete-datastore pull request #111
Opened 2021-10-12 09:46 UTC by KhaledBousrih

2021-11-16 08:53 UTC, Souleymane-T requested changes

2021-11-16 09:03 UTC, KhaledBousrih commented on docs/filters.md
> +- **Filter exact value:** (Applied on all fields within the `filter_fields`) by using a scrict equality (`field_name=field_value`) and returns all instances that have `field_value` as a value for `fi
resolved, thanks

2021-11-16 09:10 UTC, Souleymane-T approved these changes

2021-11-16 19:40 UTC, lcognat requested changes

2021-11-16 19:40 UTC, lcognat commented on concrete_datastore/api/v1/filters.py
> +            {param[:-1]: value}
ok got it, str without last char

2021-11-16 19:40 UTC, lcognat commented on concrete_datastore/api/v1/filters.py
> +                    f'{" (to exclude)" if neg=="!" else ""}'
spacing should be corrected

2021-11-16 19:40 UTC, lcognat commented on concrete_datastore/api/v1/filters.py
> +                'description': f'String{" (to exclude)" if neg=="!" else ""}',
spacing should be corrected

2021-11-16 19:40 UTC, lcognat commented on concrete_datastore/api/v1/filters.py
> +                    f'{" (to exclude)" if neg=="!" else ""}'
spacing should be corrected

2021-11-16 19:40 UTC, lcognat commented on concrete_datastore/api/v1/filters.py
> +                            f'{" (to exclude)" if neg=="!" else ""}'
spacing should be corrected

2021-11-16 19:40 UTC, lcognat commented on concrete_datastore/api/v1/filters.py
> +                    f'UID of the FK{" (to exclude)" if neg=="!" else ""}'
spacing should be corrected

2021-11-17 05:50 UTC, KhaledBousrih commented on concrete_datastore/api/v1/filters.py
> +                    f'{" (to exclude)"if neg=="!" else ""}'
corrected

2021-11-17 05:50 UTC, KhaledBousrih commented on concrete_datastore/api/v1/filters.py
> +                    f'{" (to exclude)" if neg=="!" else ""}'
corrected

2021-11-17 05:50 UTC, KhaledBousrih commented on concrete_datastore/api/v1/filters.py
> +                    f'{" (to exclude)" if neg=="!" else ""}'
corrected

2021-11-17 05:50 UTC, KhaledBousrih commented on concrete_datastore/api/v1/filters.py
> +                    f'UID of the FK{" (to exclude)" if neg=="!" else ""}'
corrected

2021-11-17 05:51 UTC, KhaledBousrih commented on concrete_datastore/api/v1/filters.py
> +                            f'{" (to exclude)" if neg=="!" else ""}'
corrected

2021-11-17 05:51 UTC, KhaledBousrih commented on concrete_datastore/api/v1/filters.py
> +                'description': f'String{" (to exclude)" if neg=="!" else ""}',
corrected

2021-11-17 05:53 UTC, KhaledBousrih commented on concrete_datastore/api/v1/filters.py
> +            {param[:-1]: value}
yes, to remove the `!` at the end of the param

2022-01-28 17:20 UTC, merged